import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/assets">Assets</Link>
        </li>
        <li>
          <Link to="/signupdesktop">SignUpDesktop</Link>
        </li>
        <li>
          <Link to="/logindesktop">LoginDesktop</Link>
        </li>
        <li>
          <Link to="/homedesktop">HomeDesktop</Link>
        </li>
        <li>
          <Link to="/blogpostdesktop">BlogPostDesktop</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
